services:
  rust_docker_sandbox:
    build: .
    ports:
      - '6969:6969'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib&postgresql/data

volumes:
  postgres_data: